services:
  - type: web
    name: testovoe5
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: python manage.py migrate --noinput && python manage.py seed_demo_data && gunicorn config.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.12.10"
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: STRIPE_PUBLISHABLE_KEY_USD
        sync: false
      - key: STRIPE_SECRET_KEY_USD
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY_EUR
        sync: false
      - key: STRIPE_SECRET_KEY_EUR
        sync: false
